// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://ydsavvndkmhkbcpkqsdq.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlkc2F2dm5ka21oa2JjcGtxc2RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMzNTExMDAsImV4cCI6MjA0ODkyNzEwMH0.KXdkpgGytuXtrEwET1YmLjaCB_IwJxqs_DTwt1E7Xv0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);